server:
  port: 8090

spring:
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=timess, swag
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
#排除自动连接数据库的依赖
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


logging:
  level:
    org:
      springframework:
        cloud:
          gateway: warn

dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: 22223
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

