server:
  port: 8090

spring:
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=timess, swag
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
#排除自动连接数据库的依赖
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-returns: true
    publisher-confirm-type: correlated
  redis:
    port: 32700
    host: localhost
    password: L#o1DZL-%!mCR8r=aM:w
    database: 0


rabbitconfig:
  queue:
    name: "invoke.main.queue"
  exchange:
    name: "invoke.main.exchange"
  routingkey:
    name: "invoke.main.routingKey"

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: warn
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: 22223
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

